Sprint 2/step 2
andrey340/react-burger pull request #3
Opened 2023-07-15 14:09 UTC by andrey340

Для проверки спринт 1 - шаг 2
Благодарю за код ревью.
С наилучшими пожеланиями Андрей Волобуев.

For check of sprint 1 - step 2
Thanks for code review
With regards Andrey Volobuev

2023-07-15 14:49 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Созданы все необходимые типы экшенов и содержаться в контсантах
- Dnd работает хорошо
- Редьюсеры - чистые функции

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Уберите лишний диспатч GET_ORDER_REQUEST в BurgerConstructor
- следует разделить экшены относящиеся к решению конкретной задачи по файлам
- поле ингредиента `__v` не имеет никакого отношения к счетчику ингредиента, поле `__v` это это версия документа в базе данных `mongo` и не должно никак использоваться в проекте
-  в списке ингредиентов нужно выводить все ингредиенты, а не разбрасывать по категориям. Ближайшая к табам категория должна подсвечиваться. Для этого вы можете использовать хук `useInView` пакета react-intersection-observer
- Генерируйте уникальный id для ингредиентов в конструкторе. 

Подробное описание замечаний смотрите комментарии в pull-request.

**Можно лучше**
- желательно очищать конструктор после успешного получения номера заказа с сервера в блоке then, чтобы пользователь мог следующий заказ сделать, не удаляя старые ингредиенты

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-07-15 14:49 UTC, andryxxa93 commented on src/components/app/app.jsx
> +  const { ingredients, ingredientsRequest, ingredientsFailed, requestError } = useSelector(state => state.ingredients)
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-07-15 14:49 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +    dispatch({
**Необходимо исправить**
У вас `GET_ORDER_REQUEST ` уже диспатчиться в `getOrder`, делать второй раз тут нет необходимости

2023-07-15 14:49 UTC, andryxxa93 commented on src/services/actions/ingredients.js
> +import { API_INGREDIENTS, API_ORDER } from "../config";
**Надо исправить**
следует разделить экшены по файлам, на нас есть несколько задач (доменных областей) не связанных между собой - загрузка ингредиентов, оформление заказа, работа конструктор. Лучше, что бы экшены относящиеся к решению каждой были описаны в своем файле, т.к. приложение со времени будет развиваться, будет добавлять новый функционал и плохо, если придется все экшены описывать в одном файле, он будет слишком большой

В текущем приложении можно разделить на следующие файлы:
- загрузка данных ингредиентов
- работа конструктора
- открытие ингредиента в попапе
- оформление заказа

2023-07-15 14:49 UTC, andryxxa93 commented on src/services/reducers/ingredients.js
> +import {
**Надо исправить**

со временем приложение будет разрастаться, появится новый функционал, если все будет в одном рельюсере он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), например

- загрузка данных ингредиентов
- отправка заказа
- работа конструктора
- открытие модального окна ингредиента

Для объединения редьюсеров используйте combineReducers
https://redux.js.org/api/combinereducers

2023-07-15 14:49 UTC, andryxxa93 commented on src/services/reducers/ingredients.js
> +                    ? { ...elem, __v: elem.__v - 1 }
**Необходимо исправить**
поле ингредиента `__v` не имеет никакого отношения к счетчику ингредиента, поле `__v` это это версия документа в базе данных `mongo` и не должно никак использоваться в проекте

2023-07-15 14:49 UTC, andryxxa93 commented on src/services/reducers/ingredients.js
> +        bun: {
**Необходимо исправить**
Использовать моковые данные уже на данном этапе нельзя. Если хотите сразу подставить какую-то булку, то её нужно доставить из тех данных, которые вы получаете на сервере

2023-07-15 14:49 UTC, andryxxa93 commented on src/services/config.js
> +export const API_INGREDIENTS = 'https://norma.nomoreparties.space/api/ingredients';
**Можно лучше**
Достаточно создать константу с baseUrl равный - https://norma.nomoreparties.space/api/. А к нему уже конкатенировать эндпоинты - ingredients и order.

2023-07-15 14:49 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +            <Filling elem={elem} key={index} index={index} />
**Необходимо исправить**
 для атрибута key в конструкторе нужно использовать для ингредиента уникальный uuid (Вам нужно его генерировать во время сброса в зону DnD). Это можно делать с помощью библиотеки uuid https://www.npmjs.com/package/uuid.  А в key будет уже просто key={ item.uuid }

2023-07-17 15:07 UTC, andrey340 commented
Ошибки исправил.

2023-07-18 07:14 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-07-18 15:52 UTC, merged